# Generated by Django 4.0.4 on 2022-11-06 07:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('USER', 'User'), ('WORKER', 'Worker')], max_length=50)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('Star', models.JSONField(blank=True, default=[], verbose_name=models.DecimalField(blank=True, decimal_places=2, max_digits=3, validators=[django.core.validators.MaxValueValidator(5)]))),
                ('preference', models.JSONField(blank=True, default=dict)),
                ('phone_no', models.CharField(default=None, max_length=50)),
                ('address', models.TextField(default=None)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(default=None, max_length=100)),
                ('biodata', models.TextField(default=None)),
                ('no_of_jobs', models.IntegerField(default=0)),
                ('Star', models.JSONField(blank=True, default=list)),
                ('workername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
            ],
        ),
    ]
