# Generated by Django 4.1.3 on 2022-11-09 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_managers_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('phone_no', models.CharField(default=None, max_length=50)),
                ('address', models.TextField(default=None)),
                ('star', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(default=None, max_length=100)),
                ('biodata', models.TextField(default=None)),
                ('star', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('UPI', models.CharField(default=None, max_length=100)),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.userdetails')),
            ],
        ),
    ]
