# Generated by Django 4.1.3 on 2022-11-09 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userdetails_workerdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerdetails',
            name='UPI',
        ),
    ]
