# Generated by Django 4.0.4 on 2022-10-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userdata_workerdata_userprofile_role_workermore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('WORKER', 'Worker')], max_length=50),
        ),
    ]
