# Generated by Django 4.0.4 on 2023-01-06 10:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('complaint', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('profession', models.CharField(max_length=100)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('Comments', models.TextField(blank=True, default=None)),
                ('assigned', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.workerprofile')),
                ('assignedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('body', models.TextField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.taskhistory')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
